[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.testnet]
solana_program = "9sYR8qpGVRQoVH9iA4MfSnArdDQtQq3wTopD6nSBiBbg"

[provider]
cluster = "testnet"
wallet = "../../wallets/master-authority.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"

[hooks]
